name: Trigger AWS Event

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions
  push:
    branches:
      - main

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send Event to AWS API Gateway
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: $(echo -n ${{ secrets.GITHUB_WEBHOOK_SECRET }} | openssl dgst -sha256 -hmac ${{ secrets.GITHUB_WEBHOOK_SECRET }} | sed 's/^.* //')" \
            -d '{"workflow_job": {"id": 1234, "status": "queued"}, "repository": {"name": "test-aws-github-workflow"}}' \
            https://wisekqb0r8.execute-api.us-east-1.amazonaws.com/prod
          
